[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
optimizer = true
optimizer-runs = 200
remappings = [
   "forge-std/=lib/forge-std/src/",
   "solmate/=lib/solmate/src/",
   "trader-joe/=lib/joe-v2/src/",
   "openzeppelin/=lib/joe-v2/lib/openzeppelin-contracts/contracts",
   "@teleporter/=lib/icm-contracts/contracts/teleporter",
   "@transferrer/=lib/icm-contracts/contracts/ictt",
   "@subnet-evm/=lib/icm-contracts/lib/subnet-evm/contracts"
]

[rpc_endpoints]
avalanche = "https://avalanche-c-chain-rpc.publicnode.com"
avalanche-test = "https://api.avax-test.network/ext/bc/C/rpc"
coq = "https://subnets.avax.network/coqnet/mainnet/rpc"

#[etherscan]
#avalanche = { key = "${AVALANCHE_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
